config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    collection do
      post :import
    end
  end
  root "products#index"
  get "/send_mail" => "products#send_mail"
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :products
  has_many :services

  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :description, presence: true, format: { with: /\A[a-zA-Z ]+\z/ }
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
  belongs_to :area

  #validates_associated :area
  
  validates :name, presence: true
  validates :classification, presence: true
  validates :selling_price, presence: true, numericality: true
  validates :purchase_price, presence: true, numericality: true
  
  def self.to_csv
    attributes = %w(area_id id name classification selling_price purchase_price)
    CSV.generate do |csv|
      csv << attributes
      all.each do |product|
        csv << attributes.map {|attr|product.send(attr)}
      end
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :area

  validates_associated :area
  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
  validates :price, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include ::ActionController::Caching
  self.cache_store = :mem_cache_store
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require "csv"
  before_action :set_product, only: [:show, :edit, :update, :destroy]
=begin
  def import
    file = params[:file]
    return redirect_to request.referer, notice: "Only CSV files allowed" unless params[:file].content_type == "text/csv"
    file = File.open(file)
    CsvImportProductsService.new.call(file)
    redirect_to products_path, notice: "New product added successfully..."
  end
=end
  def index
    @products = Product.all
   # respond_to do |format|
   #  format.html
   # format.csv { send_data @products.to_csv }
   #   format.pdf { render template: "products/products", pdf: "products" }
   #end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create! product_params
    redirect_to products_path(@product), notice: "Product was successfully created."
  end

  def show
  end

  def edit
  end

  def update
    if @product.update! product_params
      redirect_to products_path, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy!
    redirect_to products_path, status: :ok, notice: "Product deleted successfully"
  end
=begin
   def send_mail
    UserMailer.send_mail_files.deliver_now!
    @products = Product.all
    respond_to do |format|
      format.html
      format.pdf { render template: "products/products", pdf: "products" }
    end
    redirect_to products_path
  end
=end
  private

  def product_params
    params.require(:product).permit(:area_id, :name, :classification, :selling_price, :purchase_price)
  end

  def set_product
    @product = Product.find params[:id]
    if stale?(last_modified: @product.updated_at, public: true)
    render json: @product
  end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

  <%= render partial:"partials/messages"%>
    <%= yield %>
  </body>
</html>

app/views/pages/user.html.erb
<h1>Pages#user</h1>
<p>Find me in app/views/pages/user.html.erb</p>
<% if current_user%>
<%= link_to "Sing Out", destroy_user_session_path, method: :delete%>
<% else %>
<%= link_to "Sing Up", new_user_registration_path%>
<%= link_to "Sing In", new_user_session_path%>
<% end %>

app/views/partials/_message.html.erb
<h3><%= message %></h3>

app/views/partials/_messages.html.erb
<section>
    <% flash.each do |type, message|%>
        <%= render partial:"partials/message", locals:{message:message}%>
    <%end%>
</section>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <%= form.text_field :area_id, placeholder:"area id"%><br /><br />
  <%= form.text_field :name, placeholder:"product name"%><br /><br />
  <%= form.text_field :classification, placeholder:"classification"%><br><br>
  <%= form.text_field :purchase_price, placeholder:"Selling price"%><br><br />
  <%= form.text_field :selling_price, placeholder:"Purchase price"%><br><br>
  <%= form.submit "Save"%>
<% end %>

app/views/products/_import.html.erb
<%= form_tag import_products_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import' %>
<% end %>

app/views/products/_product.html.erb
<td><%= product.area_id %></td>
<td><%= product.id %></td>
<td><%= link_to product.name, product %></td>
<td><%= product.classification %></td>
<td><%= product.purchase_price %></td>
<td><%= product.selling_price %></td>

app/views/products/edit.html.erb
<%= render partial:'form'%>

app/views/products/index.html.erb
<h1>Products</h1>
<a href= "/send_mail"> Send Mail</a>
<%= link_to "Export PDF file", products_path(format: :pdf), :target => "_blank" %>
<%= link_to "Export products", products_path(format: :csv) %>
<%= render "import" %>
<table>
  <thead>
    <tr>
      <th>area id</th>
      <th>id</th>
      <th>name</th>
      <th>classification</th>
      <th>purchase price</th>
      <th>selling price</th>
    </tr>
  </thead>
  <tbody>
   <% @products.each do |product| %>
        <tr>
          <%= render partial: "product", locals: { product: product } %>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/products/main.html.erb
<html>
<head>
<title></title>

<style type="text/css">
#BarraHTML {
background-color: #321797;
padding: 1px;
position: fixed;
width: 100%;
z-index: 10000;
}
#BarraHTML ul{
list-style-type: none;
}
#BarraHTML li{
display: inline;
text-align: center;
margin: 0 0 0 0;
}
#BarraHTML li a {
padding: 2px 7px 2px 7px;
text-decoration: none;
}
#BarraHTML li a:hover{
background-color: #321797;

}
#texto{
padding: 80px 0 0 0;
}
</style>
</head>

<body>

<div id="BarraHTML">
<ul>
<li><a href="#">
<div class= "logo" img id="logo" src="logo_veterinary.png" ></a></li>
<li><a href="#">Services</a></li>
<li><a href="#">Products</a></li>
<li><a href="#">Contact</a></li>
<li><a href="#">Blog</a></li>

<li><a href="#">
<span class="icon"><i class="fa fa-search"></i></span>
<input type="search" id="search" placeholder="Search..." /></a></li>

</div>
</ul>
</div>
<div id="texto">


</div>
</body>
</html>
<h1>main page</h1>

app/views/products/new.html.erb
<h1>New products </h1>
<%= render partial: 'form'%>

app/views/products/products.pdf.erb
<h1>Products</h1>
<table>
  <thead>
    <tr>
     <th>area id</th>
      <th>id</th>
      <th>Name</th>
      <th>Classification</th>
      <th>purchase price</th>
      <th>selling price</th>
    </tr>
  </thead>
  <tbody>
   <% @products.each do |product|%>
        <tr>
         <td><%= product.area_id %></td>
         <td><%= product.id %></td>
         <td><%= product.name%></td>
         <td><%= product.classification %></td>
         <td><%= product.purchase_price %></td>
         <td><%= product.selling_price %></td>
         </tr>
    <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
<%= @product.name %>
<%= @product.classification %>
<%= @product.purchase_price %>
<%= @product.selling_price %>
<%= link_to 'Edit product', edit_product_path(@product) %>
<%= link_to 'Delete product', product_path(@product), data: {turbo_method: :delete, turbo_confirm: 'Are you sure to remove the product?'} %>